### ISSUE TITLE
EventNotifier

### ISSUE THREAD

**Issue by Norbert515** [escamoteur/functional_listener#1]
I create my own subclass of ValueListenable which I called EventNotifier because ValueNotifier only updates the state if the new value is not equal to the old one (which doesn't work for events which might fire with the same value over time).

Any idea of how such a thing could work with these extensions?

**Comment by escamoteur** [comment]
Hmm, this would need to require to use your EventNotifier class as base of my library as I use ValueNotifier derived types in my extension methods. This would be actually quite nice, we could then add an extension method ´distinct` that filters out same values.
What do you think about an PR ;)

**Comment by SAGARSURI** [comment]
There is another package called `state_notifier`. 
https://pub.dev/packages/state_notifier

How can we use these extensions for state_notifier?

**Comment by escamoteur** [comment]
Unfortunately not because Remi wanted it to be independent of Flutter, so it does not implement `ValueListenable` which would be needed to use this package. 
It shouldn't be too difficult to fork the package and adapt it to StateNotifier
