### ISSUE TITLE
syntax for maintaining property in service2 that always reflects value of a ValueNotifier from service1

### ISSUE THREAD

**Issue by matthewkooshad** [escamoteur/functional_listener#10]
this relates to https://github.com/escamoteur/watch_it/issues/20#event-11213636266 , where i have a service2, which is needing to know about the current dark mode value. The dark mode ValueNotifier is in service1. 

below is what i'm trying. could you help me with a short syntax to achieve it?
if i do this:
`final _isDarkMode = GetIt<ThemeState>().isDarkMode.map((x) => x);`
then, i get a ValueListenable.

i'm wanting to have some `Color get` property that will use this _isDarkMode.value to return the Color. but, it appears such a getter property is not reflecting the latest value.

**Comment by escamoteur** [comment]
Could you please share a small project that shows what you try to do and invite me to the repository.
The I probably can help better
Am 12. Dez. 2023, 17:27 +0100 schrieb Matthew Kooshad ***@***.***>:

**Comment by matthewkooshad** [comment]
i think i have no problem with the syntax i gave in this thread now, so i will close this now. thanks
