### ISSUE TITLE
How to use combineLatest for more than 2 valuenotifier?

### ISSUE THREAD

**Issue by SAGARSURI** [escamoteur/functional_listener#5]
Hey @escamoteur 
I have a use case where I need to combine 4 valuenotifier. But with the current implementation of `combineLatest` it's not possible. Any plans for having something like these versions of `combineLatest`?
`combineLatest3`
`combineLatest4`

**Comment by escamoteur** [comment]
Hi, so far I didn't had the need for it, but surely we could add it.

The other possibility that you have is to cascade the combinedLatest operator.

**Comment by SAGARSURI** [comment]
Let me see if I can submit a PR for this. Will that work for you?

**Comment by escamoteur** [comment]
sure, I'm happy about any contribution 😊
